### ISSUE TITLE
半角假名错误翻译

### ISSUE THREAD

**Issue by Wigglex2** [fkiliver/RPGMaker_LLM_Translator#1]
> 原文: 遠景の画像ﾌｧｲﾙ名 => 翻译: 远景的影像ｚｏｎｍａｉｎｇ
> 原文: 再生中BGMﾌｧｲﾙ名 => 翻译: 再生中BGMｓｅｎａｍｅｔｉｏｎｎｅ

可以用`unicodedata.normalize('NFKC', foo)`统一转换成全角假名

**Comment by fkiliver** [comment]
感谢反馈，现在会在翻译前将假名格式化为全角
