### ISSUE TITLE
建议增加对Translator++的支持

### ISSUE THREAD

**Issue by ABSllk** [fkiliver/RPGMaker_LLM_Translator#20]
用类似的方式用Translator++将待翻译文本导出，翻译后再导入，通过Translator++注入游戏，就不用每次还要启动mtool了。

**Comment by fkiliver** [comment]
会考虑添加，最近比较忙，可能会等sakura0.10正式版后再动工

**Comment by ABSllk** [comment]
那我写一下吧,最近比较空

**Comment by yujianke100** [comment]
@ABSllk 老板，你加功能的时候顺手把main.py兼容多API的设置给改了啊。不如改回去方便两个main兼容一套config？

**Comment by ABSllk** [comment]
> @ABSllk 老板，你加功能的时候顺手把main.py兼容多API的设置给改了啊。不如改回去方便两个main兼容一套config？

最新版本我已经改过来了,只不过我的pr还没有被并入. 当初改掉是因为这个有点bug,有时候会把整个字符串当成数组,然后请求的endpoint就变成了第一个字符'h'

**Comment by yujianke100** [comment]
> > @ABSllk 老板，你加功能的时候顺手把main.py兼容多API的设置给改了啊。不如改回去方便两个main兼容一套config？
> 
> 最新版本我已经改过来了,只不过我的pr还没有被并入. 当初改掉是因为这个有点bug,有时候会把整个字符串当成数组,然后请求的endpoint就变成了第一个字符'h'

好嘞，感谢
