### ISSUE TITLE
ngrok拒绝连接问题

### ISSUE THREAD

**Issue by ABSllk** [fkiliver/RPGMaker_LLM_Translator#23]
每次翻译一段时间后ngrok的域名就会拒绝连接,换代理也没用,感觉像是被ban了,ngrok页面上没有发现什么异常
总不能是请求过于频繁吧......

**Comment by getoutnow2013** [comment]
我翻譯一個遊戲有4000行文本（當然有長有短）
用 ngrok+tgw+kaggle 跑了7小時跑完，沒有任何拒絕連接
（我沒有設任何代理）

所以我覺得主要因素應該是你代理的問題

**Comment by ABSllk** [comment]
可是后面我关闭代理了,仍然没用,下次我试试全程直连吧

**Comment by getoutnow2013** [comment]
> 可是后面我关闭代理了,仍然没用,下次我试试全程直连吧

SakuraLLM 模型頁面發布wiki中，第三種方式：直接使用 ngrok+kaggle+llama 的方法
用目前最新的 **main.py (或 main_dev.py)** 去跑
模型用目前最新版的 **sakura-14b-qwen2beta-v0.9.2-q6k.gguf**
**用單一執行緒，不使用多執行緒**

大概跑 250-350 次左右，ngrok 就會爆掉無法進入
最後只能重起 kaggle 虛擬機，才能繼續再翻譯（但一樣又是250-350次左右就爆掉）
![20240810_SAK_002](https://github.com/user-attachments/assets/03f0d924-721c-4d18-a014-8d9bb892cf6c)
![20240810_SAK_003](https://github.com/user-attachments/assets/39989d3d-6d89-495b-977e-4e91922a9bc4)
我試了幾個禮拜都還是這種老樣子....
**這個問題我也發布到 SakuraLLM GitGub 的問題區了**

然後改採我之前用的：ngrok+kaggle+tgw 的方式
和上述條件一樣，跑個幾千次都沒有問題。
![20240810_TGW_001](https://github.com/user-attachments/assets/c2501ea0-06fd-41e1-9aec-77b956bf5fcf)
![20240810_TGW_003](https://github.com/user-attachments/assets/6dfe290a-b95d-48fa-a918-44e5dd591a1b)

但是 main.py 如同我另外一篇講的， role:system 的部份的提示詞，要拿到 role:user 裡面
修改前：
![20240810_SAK_004](https://github.com/user-attachments/assets/262347f4-c499-4ee2-bf42-bc42c33de9fc)
修改後：
![20240810_SAK_005](https://github.com/user-attachments/assets/5a8a4209-7b97-4139-a144-937c0f948b02)

**Comment by fkiliver** [comment]
项目已重构
