### ISSUE TITLE
目前翻譯時，切割為多行的討論

### ISSUE THREAD

**Issue by getoutnow2013** [fkiliver/RPGMaker_LLM_Translator#26]
main.py 0.3.5 的版本
在送出原文進行翻譯前，會先對原文切割 \r, \n, \r\n，切成多行後（如果有多行）
再逐行進行發送API進行翻譯。

這樣做的優點是，能很好的保持和原文相同換行的格式

缺點則是：
1.上下文的聯繫會中斷（不一定可以銜接的很好）
2.遇到退化時，格式仍然還是會有問題。
3.透過 Ngrok 穿透到 Kaggle 會有困擾
Ngrok 不曉得何時開始，改成「一個月」限制只能發「20,000」筆 Request
所以遇到原文多行，例如原文有20行，就會變成這一筆原文就發了20筆 Request

想討論的是，就大家的經驗來說
如果不將原文切割多行再發送，以目前 SakuraLLM 13B 或 14B 的模型來說
會經常遇到無法保留「和原文相同的多行格式」嗎？

如果並不一定會無法保留格式，
那麼感覺上優點並不足取代缺點的部份。
還是說分拆多行，有其他的優點嗎？

**Comment by fkiliver** [comment]
主要是不拆分的话，一些游戏会出现显示错误。这个问题是准备通过把一段文本已翻译部分作为历史上文添加到prompt内来解决。

**Comment by getoutnow2013** [comment]
加到 prompt 這個方式
如果是使用 ngrok+kaggle 的話

1.使用SakuraLLM給的腳本，來啟動llama接收api來翻譯，可以用prompt，但request會有炸通道的問題，大概翻譯250-350次就會掛掉。

2.使用B站up主給的tgw腳本，來啟動tgw接收api來翻譯，request中就必須拿掉prompt，但不會炸通道，翻譯上萬次都不會斷，可是會因為斷行問題導致翻譯變得很破碎、不連貫。

我在另一篇的issue裡面有描寫上述情況了
