### ISSUE TITLE
处理特殊字符会很慢

### ISSUE THREAD

**Issue by 1762011099** [fkiliver/RPGMaker_LLM_Translator#6]
我也不清楚为什么会出现这个特殊符号，，但导出的就是有。看能不能在post的时候给改善下。
<img width="192" alt="PixPin_2024-01-22_14-38-04" src="https://github.com/fkiliver/RPGMaker_LLM_Translator/assets/157030358/6db42363-1678-43ae-a731-986eaf66cbdb">
源文件
[ManualTransFile.json](https://github.com/fkiliver/RPGMaker_LLM_Translator/files/14006131/ManualTransFile.json)

**Comment by fkiliver** [comment]
怎么看着像是编码错误

**Comment by fkiliver** [comment]
> 我也不清楚为什么会出现这个特殊符号，，但导出的就是有。看能不能在post的时候给改善下。 <img alt="PixPin_2024-01-22_14-38-04" width="192" src="https://private-user-images.githubusercontent.com/157030358/298484040-6db42363-1678-43ae-a731-986eaf66cbdb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NTY5MzgsIm5iZiI6MTcwNjk1NjYzOCwicGF0aCI6Ii8xNTcwMzAzNTgvMjk4NDg0MDQwLTZkYjQyMzYzLTE2NzgtNDNhZS1hNzMxLTk4NmVhZjY2Y2JkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QxMDM3MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jM2Q2YTYwOTBkZTgzYWYyZWIxNWY0NjAyMjlhZjVmYzhkM2QzNzVjYjQzZDMxNDUxOTk2MWU2YmMwODQ5OTc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1RhX-A4rhWo2eAluc6rqd7DEVxk6lc6KdMCqG-PYOCo"> 源文件 [ManualTransFile.json](https://github.com/fkiliver/RPGMaker_LLM_Translator/files/14006131/ManualTransFile.json)

检查了一下，文本本身带的制表符号，会导致模型退化。不是常见现象，没法解决，只能等。
